# Generated by Django 3.2.2 on 2021-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_seller_total_earning'),
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imformation',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='productFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('feedback_by', models.ManyToManyField(related_name='customer_name', to='account.customer')),
                ('product', models.ManyToManyField(related_name='product_name', to='product.product')),
            ],
        ),
    ]
