# Generated by Django 3.2.2 on 2021-05-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210513_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productFeedback',
        ),
    ]
