# Generated by Django 3.2.2 on 2021-05-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_seller_total_earning'),
        ('product', '0004_delete_productfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='productFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to='account.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='product.product')),
            ],
        ),
    ]
